comment/urls.py
from django.urls import path
from .views import *

app_name = 'comment'
urlpatterns = [

    path('add/<int:title_id>', add, name='add'),

]

cs/urls.py
from django.urls import path
# from django.contrib import
from .views import *

app_name='cs'
urlpatterns = [
    path('index',index,name='index'),
    path('classSchedule', classSchedule,name='classSchedule'),
    path('javaDocumentation', javaDocumentation,name='javaDocumentation'),
    path('javaExam',javaExam,name='javaExam'),
]

forum/urls.py
from django.urls import path
from .views import *

app_name = 'forum'
urlpatterns = [
    path('index', index, name='index'),
    path('add', add, name='add'),
    path('detail/<int:title_id>/', detail,name='detail'),
    path('update/<int:title_id>/', update,name='update'),
    path('delete/<int:title_id>/', delete,name='delete'),
]

myforum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("firstTest.urls")),
    path('forum/', include("forum.urls")),
    path('user/', include("user.urls")),
    path('cs/', include('cs.urls')),
    path('loveBar/', include('loveBar.urls')),
    path('xlTree/', include('xlTree.urls')),
    path('comment/', include('comment.urls')),
    path('friends/',include('friends.urls')),
    # path('get_file/')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *
app_name='user'
urlpatterns = [
    path('register',register,name='register'),
    path('login',login,name='login'),
    path('logout',logout,name='logout'),
    path('index',index,name='index'),
    path('modifyUserInfo',modify,name='modify'),
    path('changePassword',changePassword,name='changePassword'),
    path('information/<str:username>/',information,name='information'),
    path('notifications',notifications,name='notifications'),
    path('val_mes',val_mes,name='val_mes'),
    path('search_user',search_user,name='search_user'),
]

forum/models.py
from django.db import models
from user.models import UserInfo
# Create your models here.
'''
    发布者，主题，内容，时间，修改时间，删除,注册后台
'''
class Forum(models.Model):

    title=models.CharField(verbose_name='主题',max_length=100)
    content=models.TextField(verbose_name='内容')
    created_time=models.DateTimeField(verbose_name='发布时间',auto_now_add=True)
    updated_time=models.DateTimeField(verbose_name='更新时间',auto_now=True)
    user=models.ForeignKey(UserInfo,on_delete=models.CASCADE)

    class Meta:
        db_table='forum'
        verbose_name='论坛话题'
        verbose_name_plural='论坛话题'
        ordering=["-created_time"]
    def __str__(self):
        if len(self.title)<=10:
            return self.title
        else:
            return self.title[:10]+"..."

forum/views.py
from django.shortcuts import render, HttpResponse, Http404, HttpResponseRedirect

# Create your views here.
from user.views import check_login
from .models import *
from django.views.decorators.csrf import csrf_exempt


@check_login
def index(request):
    items = Forum.objects.order_by("-created_time")
    return render(request, "forum/index.html", locals())


@check_login
def detail(request, title_id):
    try:
        item = Forum.objects.get(id=title_id)
    except:
        return Http404
    id = item.id
    title = item.title
    author = item.user
    content = item.content
    created_time = item.created_time
    updated_time = item.updated_time
    comments = item.comment_set.all()
    is_author = False
    if request.session['userName'] == item.user.username:
        is_author = True
    return render(request, 'forum/detail.html', locals())


@check_login
def update(request, title_id):
    try:
        item = Forum.objects.get(id=title_id)
    except:
        return Http404
    if request.method == 'GET':
        return render(request, 'forum/update.html', locals())
    elif request.method == 'POST':
        item.content = request.POST.get('content')
        # item.created_time=
        item.save()
        return HttpResponseRedirect(f'/forum/detail/{item.id}/')


@check_login
def add(request):
    if request.method == 'GET':
        return render(request, 'forum/add.html')
    elif request.method == 'POST':
        user = UserInfo.objects.get(username=request.session['userName'])
        data = request.POST
        title = data.get('title')
        content = data.get('content')
        Forum.objects.create(user=user, title=title, content=content)
        return HttpResponseRedirect('/forum/index')


@check_login
def delete(request, title_id):
    try:
        item = Forum.objects.get(id=title_id)
        item.delete()
        return HttpResponseRedirect('/forum/index')
    except:
        return Http404

forum/templates/forum/add.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>添加话题</title>
    <link href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.js"></script>
 
</head>

<body>
    <div id="info_box_fail" class="alert alert-danger alert-dismissible w-50 mx-auto mt-5" hidden>
        <strong>失败!</strong> 标题和内容不能为空!
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    <div class="mt-5">
        <form action="{% url 'forum:add' %}" method="post" class="form-horizontal" id="form">
            <div class="w-25 mx-auto mb-3"><input id='title' class="text-center form-control text-warning" type="text"
                    name="title" maxlength="100" placeholder="请输入话题" maxlength="20"></div>
            <div class="w-50 mx-auto"><textarea name="content" id="content" class="form-control text-success bg-dark"
                    cols="30" rows="10" placeholder="在此添加内容..." id="content"></textarea></div>
            <center class="mt-3"><input type="button" value="添加" id="submit_btn" class="btn btn-primary"></center>

            {% csrf_token %}
        </form>
    </div>
    <script>
        $("#submit_btn").bind("click", function(){
            title=$("#title").val();
            content=$("#content").val();
           if (title=="" || content=="") {
               $("#info_box_fail").prop("hidden",false);
           }
           else {
                alert("成功添加话题！")
                $("#form").submit();
           }
        });
    </script>
</body>

</html>

forum/templates/forum/detail.html
<!DOCTYPE html>
<html lang="zh-hans">

<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.js"></script>
</head>

<body class="bg-secondary">
    <div class="container mt-3">
        <div class="mx-auto text-center mb-3">
            <span class="text-dark h3 ">{{ title }}&nbsp;&nbsp;
                <a href="#comments" class="btn btn-dark btn-sm text-warning" data-bs-toggle="collapse">展开评论区</a></span>
        </div>
        <div class="mx-auto w-75 alert alert-secondary p-3">
            <div class="mb-3">
                {{ content }}
            </div>
             作者:
             <a href="{% url 'user:information' author.username %}" class="text-decoration-none">
                @{{ author }}
            </a>
            <small>{{ created_time }}</small>
        </div>
        
        <div id="comments" class="collapse">
            {% for comment in comments %}
            
            <div class="alert alert-success mx-auto w-75 mt-3">
                <p class="mb-2">
                    {{ comment.content }}
                </p>
                <a href="{% url 'user:information' comment.user.username %}" class="text-decoration-none">
                    @{{ comment.user.nickname }}
                </a>
                &nbsp;
                <small>{{ comment.created_time }}</small>
            </div>
            
            {% empty %}
            <div class="alert alert-warning mx-auto w-75 mt-3 ">
                <h6>还没有评论快去评论吧!</h6>
            </div>
            {% endfor %}
        </div>
       
        <center>
            <a href="{% url 'comment:add' id %}" class="btn btn-primary">评论</a>
            {% if is_author %}
            <a href="{% url 'forum:update' id %}" class="btn btn-warning">修改</a>
            <button id="delete_forum" class="btn btn-danger">删除</button>
            <script>
                $("#delete_forum").bind("click", function () {
                    if (confirm("确定删除该话题吗？")) {
                        window.location.replace("{% url 'forum:delete' id %}");
                    }
                });
            </script>
            {% endif %}
        </center>
    </div>

</body>

</html>

forum/templates/forum/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>论坛</title>
    {% endblock title %}
    {% block bgimg %}
    background-image: url("{% static 'imgs/forum.png' %}");
    {% endblock bgimg %}
    {% block style %}
    <link href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.js"></script>
    {% endblock style %}

</head>

<body>
    {% block content %}
    <br><br><br><br><br><br>
    <center>
        <h4>
            <em>
                <strong>欢迎来到西林论坛！</strong>
            </em>
            &nbsp;&nbsp;&nbsp;
            <a href="{% url 'forum:add' %}" class="btn btn-primary" data-bs-toggle="tooltip" title="点击添加话题">添加话题</a>
        </h4>

    </center>
    <table class="table table-striped table-bordered table-hover w-75 mx-auto">
        <tr class="text-center">
            <th>话题</th>
            <th>发布者</th>
            <th>发布时间</th>
            <th>更新时间</th>
        </tr>
        {% for item in items %}
        <tr>
            <td>
                <a href="{% url 'forum:detail' item.id %}" class="text-decoration-none" data-bs-toggle="tooltip" title="点击查看详情">{{ item }}</a>
            </td>
            <td class="text-center">
                <a href="{% url 'user:information' item.user.username %}" class="text-decoration-none" data-bs-toggle="tooltip" title="点击去往主页">
                    {{ item.user.nickname }}
                </a>
            </td>
            <td class="text-center"><small>{{ item.created_time }}</small></td>
            <td class="text-center"><small>{{ item.updated_time }}</small></td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">还没有话题哦</td>
        </tr>
        {% endfor %}

    </table>
    {% endblock content %}
</body>

</html>

forum/templates/forum/update.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>更新内容</title>
    <style>
        p {
            text-align: center;
        }

        #title {
            width: 200px;
            height: 30px;
        }

        #content {
            width: 500px;
            height: 300px;
        }
    </style>
</head>

<body>
    <form action="{% url 'forum:update' item.id %}" method="post">
        <p><input id='title' type="text" name="title" maxlength="100" value="{{ item.title }}" maxlength="20" readonly></p>
        <p><textarea name="content" id="content" cols="30" rows="10" ></textarea></p>
        <p><input type="submit" value="提交"></p>

        {% csrf_token %}
    </form>
</body>
<script>
        document.getElementById("content").value="{{ item.content }}";
 </script>

</html>