cs/urls.py
from django.urls import path
# from django.contrib import
from .views import *

app_name='cs'
urlpatterns = [
    path('index',index,name='index'),
    path('classSchedule', classSchedule,name='classSchedule'),
    path('javaDocumentation', javaDocumentation,name='javaDocumentation'),
    path('javaExam',javaExam,name='javaExam'),
]

forum/urls.py
from django.urls import path
from .views import *

app_name = 'forum'
urlpatterns = [
    path('index', index, name='index'),
    path('add', add, name='add'),
    path('detail/<int:title_id>/', detail,name='detail'),
    path('update/<int:title_id>/', update,name='update'),
    path('delete/<int:title_id>/', delete,name='delete'),
]

friends/urls.py
from django.urls import path

from forum.views import delete
from .views import *

app_name = 'friends'
urlpatterns = [
    path('friends_list', friends_list, name='friends_list'),
    path('add_friend/<str:username>', add_friend, name='add_friend'),
    path('agree', agree, name="agree"),
    path('reject', reject, name='reject'),
    path('del_val_mes', del_val_mes, name="del_val_mes"),
    path('delete_friend/<str:username>', delete_friend, name='delete_friend'),
    path('dialogues', dialogues, name='dialogues'),
    path('detail_dialogues', detail_dialogues, name='detail_dialogues'),
    path('send_message', send_message, name='send_message'),
    path('set_remark_name', set_remark_name, name='set_remark_name'),
]

myforum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("firstTest.urls")),
    path('forum/', include("forum.urls")),
    path('user/', include("user.urls")),
    path('cs/', include('cs.urls')),
    path('loveBar/', include('loveBar.urls')),
    path('xlTree/', include('xlTree.urls')),
    path('comment/', include('comment.urls')),
    path('friends/',include('friends.urls')),
    # path('get_file/')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *
app_name='user'
urlpatterns = [
    path('register',register,name='register'),
    path('login',login,name='login'),
    path('logout',logout,name='logout'),
    path('index',index,name='index'),
    path('modifyUserInfo',modify,name='modify'),
    path('changePassword',changePassword,name='changePassword'),
    path('information/<str:username>/',information,name='information'),
    path('notifications',notifications,name='notifications'),
    path('val_mes',val_mes,name='val_mes'),
    path('search_user',search_user,name='search_user'),
]

user/models.py
from django.db import models

# Create your models here.
# # 引入默认的用户模型类
# from django.contrib.auth.models import AbstractUser
#
#
# class UserProfile(AbstractUser):
#     # 昵称
#     # CharField的max_length是必填参数
#     # verbose_name 后台管理界面中显示的字段名
#     # 用户名
#     userName = models.CharField(verbose_name='用户名', max_length=20)
#     # 密码
#     password = models.CharField(verbose_name='密码', max_length=32)
#     nickName = models.CharField(verbose_name='昵称', default='', max_length=20)
#     # 生日
#     # blank=True 前端表单中的数据可以为空
#     birthday = models.DateTimeField(verbose_name='生日', null=True, blank=True)
#     # 性别
#     gender=models.CharField(verbose_name='性别',max_length=1)
#
#     # 住址
#     # address = models.CharField(max_length=50, verbose_name='地址', default='')
#
#     # 电话
#     # mobile = models.CharField(max_length=11, verbose_name='手机', default='')
#     # 邮箱
#     # email= models.EmailField(verbose_name="邮箱")
#
#     # 用户头像
#     # image = models.ImageField(upload_to='images/%Y/%m', default='image/default.png', verbose_name='头像')
#
#     class Meta:
#         db_table = 'Users'
#         # 后台管理界面中显示的表的信息
#         verbose_name = '用户信息'
#         # 复数
#         verbose_name_plural = '用户信息'
class UserInfo(models.Model):
    username=models.CharField(verbose_name='用户名',max_length=20,unique=True)
    password=models.CharField(verbose_name='密码',max_length=32)
    nickname=models.CharField(verbose_name='昵称',max_length=20,default='无名氏')
    gender=models.CharField(verbose_name='性别',max_length=1,choices=(('M','男'),('F','女')))
    age=models.IntegerField(verbose_name='年龄',default=18)
    # birthday=models.DateTimeField(verbose_name='出生日期',default='2021-01-01')
    email=models.EmailField(verbose_name='邮箱',max_length=30,unique=True)
    created_time=models.DateTimeField(verbose_name='注册时间',auto_now_add=True)
    class Meta:
        db_table='userinfo'
        verbose_name='普通用户',
        verbose_name_plural='普通用户'
    def __str__(self):
        return self.username

friends/views.py
import json

from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.http import Http404

# Create your views here.
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from user.views import check_login
from user.models import UserInfo
from .models import *
from django.db.models import Q, F


@check_login
def friends_list(request):
    username = request.session['userName']

    # friends=FriendRelationship.objects.filter(Q(FriendRelationship.username_A=='username'
    #                                             | Q(FriendRelationship.username_B)))
    friends = [{"username": fr.username_B, "remarkName": fr.remark_name_B} for fr in
               FriendRelationship.objects.filter(username_A=username)]
    friends += [{"username": fr.username_A, "remarkName": fr.remark_name_A} for fr in
                FriendRelationship.objects.filter(username_B=username)]

    return render(request, 'friends/friends_list.html', locals())


@check_login
def add_friend(request, username):
    sender = UserInfo.objects.get(username=request.session['userName'])
    receiver = UserInfo.objects.get(username=username)
    if request.method == 'GET':
        return render(request, 'friends/validationMessage.html', locals())
    elif request.method == 'POST':
        # 添加好友时在两个用户之间建立一个验证消息会话
        # 即在数据库中新建一条会话记录
        content = request.POST.get('content', f'{sender}请求添加你为好友！')
        ValidationMessages.objects.create(sender=sender, receiver=receiver, content=content)
        print(content)
        return HttpResponseRedirect('/friends/friends_list')


@csrf_exempt
def agree(request):
    if request.method == "POST":
        data = request.POST
        inform_id = data.get('id')
        sender = UserInfo.objects.get(username=data.get("sender"))
        receiver = UserInfo.objects.get(username=data.get("receiver"))

        '''
            该条验证消息对接收者已经没有意义
            讲该条验证消息的是否同意设置为Y,修改验证消息为“xxx同意了你的好友请求”,
            互换接受者和发送者身份,这样发送者就会收到来自接收者的回馈消息
        '''
        val_mes = ValidationMessages.objects.get(id=inform_id)
        val_mes.isAgreed = 'Y'
        val_mes.content = f"{receiver.username}通过了你的好友验证！"
        val_mes.sender, val_mes.receiver = receiver, sender
        val_mes.save()

        # 若fr关系表中没有这对关系则在fr表中建立sender和receiver的朋友关系
        try:
            FriendRelationship.objects.get(username_A=sender.username, username_B=receiver.username)
        except:
            try:
                FriendRelationship.objects.get(username_A=receiver.username, username_B=sender.username)
            except:
                FriendRelationship.objects.create(username_A=sender.username, username_B=receiver.username,
                                                  remark_name_A=sender.username, remark_name_B=receiver.username)
        return HttpResponse(200)


@csrf_exempt
def reject(request):
    if request.method == "POST":
        data = request.POST
        inform_id = data.get('id')
        sender = UserInfo.objects.get(username=data.get("sender"))
        receiver = UserInfo.objects.get(username=data.get("receiver"))

        '''
            该条验证消息对接收者已经没有意义
            讲该条验证消息的是否同意设置为N,修改验证消息为“xxx婉拒了你的好友请求”,
            互换接受者和发送者身份,这样发送者就会收到来自接收者的回馈消息
        '''
        val_mes = ValidationMessages.objects.get(id=inform_id)
        val_mes.isAgreed = 'N'
        val_mes.content = f"{receiver.username}婉拒了你的好友请求！"
        val_mes.sender, val_mes.receiver = receiver, sender
        val_mes.save()
        print('123')

        return HttpResponse(200)


@csrf_exempt
def del_val_mes(request):
    if request.method == "POST":
        val_mes_id = request.POST.get('id')
        ValidationMessages.objects.get(id=val_mes_id).delete()
        # 返回一个响应防止报错
        return HttpResponse(200)


@check_login
def delete_friend(request, username):
    # 获取session中的当前用户名和参数用户名
    # 在数据库中删除这对好友关系
    username_myself = request.session.get('userName')
    print(username)
    try:
        fr = FriendRelationship.objects.get(username_A=username_myself, username_B=username)
        fr.delete()
        return HttpResponseRedirect('/friends/friends_list')
    except:
        try:
            fr = FriendRelationship.objects.get(username_B=username_myself, username_A=username)
            fr.delete()
            return HttpResponseRedirect('/friends/friends_list')

        except:
            return render(request, '404.html')


@check_login
def dialogues(request):
    '''
    查询出与该用户有过聊天的用户,去重后渲染出对话框
    '''
    user_id = request.session.get('userID')
    user = UserInfo.objects.get(id=user_id)
    receivers = list(map(lambda x: x.receiver, Dialogue.objects.filter(sender=user)))
    senders = list(map(lambda x: x.sender, Dialogue.objects.filter(receiver=user)))
    related_users = list(set(receivers + senders))

    dialogues_list = []  # 定义一个空列表存需要渲染的对话框数据
    for related_user in related_users:
        # 根据相关用户查询出与该用户最新一条消息记录和发送时间
        dia = Dialogue.objects.filter(
            Q(sender=related_user) & Q(receiver=user) | Q(sender=user) & Q(receiver=related_user)).order_by(
            '-send_time')[0]
        dialogues_list.append({
            "user": related_user,
            "message": dia.message,
            "send_time": dia.send_time,

        })

    return render(request, 'friends/dialogues.html', context={'dialogues': dialogues_list})


@check_login
def detail_dialogues(request):
    '''
    查询出这两个用户之间的所有对话
    按时间排序渲染在对话框中
    '''
    try:
        user = UserInfo.objects.get(username=request.session.get('userName'))
        related_user = UserInfo.objects.get(username=request.GET.get('username'))

        dialogue_objects = Dialogue.objects.filter(
            Q(sender=related_user) & Q(receiver=user) | Q(sender=user) & Q(receiver=related_user)).order_by(
            'send_time')
        dialogues_list = []
        for dialogue_object in dialogue_objects:
            dialogues_list.append({
                "username": dialogue_object.sender.username,
                "message": dialogue_object.message,
                "send_time": str(dialogue_object.send_time),
            })
        print(json.dumps(dialogues_list))
        return HttpResponse(json.dumps(dialogues_list))
    except:
        return render(request, '404.html')


# @check_login
@csrf_exempt
def send_message(request):
    '''
    接受ajax请求,存储发送过来的ajax对话数据
    '''
    sender_name = request.POST.get("send_name")
    receiver_name = request.POST.get("receiver_name")
    sender = UserInfo.objects.get(username=sender_name)
    receiver = UserInfo.objects.get(username=receiver_name)
    message = request.POST.get("message")
    Dialogue.objects.create(sender=sender, receiver=receiver, message=message)
    return HttpResponse(200)


# TODO:解决csrf_exempt装饰的视图函数的跨站请求伪造问题

@csrf_exempt
def set_remark_name(request):
    data = request.POST
    user = data.get('username')
    friend = data.get('friendUsername')
    remarkName = data.get('remarkName')
    print(user,friend,remarkName)
    try:
        fr = FriendRelationship.objects.get(username_A=user, username_B=friend)
        fr.remark_name_B = remarkName
        fr.save()
        return HttpResponse("success")
    except:
        try:
            fr = FriendRelationship.objects.get(username_A=friend, username_B=user)
            fr.remark_name_A = remarkName
            fr.save()
            return HttpResponse("success")
        except:
            return HttpResponse(404)

user/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
import json
# Create your views here.
from django.views.decorators.csrf import csrf_exempt

from forum.models import Forum
from .models import UserInfo
from hashlib import md5
from friends.models import *
from django.db.models import F, Q


def register(request):
    if request.method == 'GET':
        return render(request, 'user/register.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        if {'username': username} in UserInfo.objects.values('username'):
            return HttpResponse('用户名已存在！')
        password = request.POST.get('password')
        if password:
            m_password = md5()
            m_password.update(password.encode())
            password = m_password.hexdigest()
        nickname = request.POST.get('nickname')
        gender = request.POST.get('gender')
        # print(gender)

        age = request.POST.get('age')
        email = request.POST.get('email')
        try:
            UserInfo.objects.create(username=username, password=password,
                                    nickname=nickname, gender=gender,
                                    age=age, email=email)
        except:
            return HttpResponse('用户名或邮箱已被注册')
        return render(request, 'user/login.html', locals())


def login(request):
    if request.method == 'GET':
        return render(request, 'user/login.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        try:
            user = UserInfo.objects.get(username=username)
        except Exception as e:
            return HttpResponse('用户名或密码错误')
        password = request.POST.get('password')
        m_password = md5()
        m_password.update(password.encode())
        password = m_password.hexdigest()
        if password == user.password:
            request.session['userName'] = username
            request.session['userID'] = user.id
            return HttpResponseRedirect('/')
        else:
            return HttpResponse('用户名或密码错误')


def check_login(func):
    def wrapper(request, *args, **kwargs):
        if 'userName' in request.session and 'userID' in request.session:

            return func(request, *args, **kwargs)
        else:
            return HttpResponseRedirect('/user/login')

    return wrapper


def logout(request):
    if request.session.get('userName'):
        del request.session['userName']
    if request.session.get('userID'):
        del request.session['userID']
    return HttpResponseRedirect('/')


@check_login
def index(request):
    username = request.session['userName']
    user = UserInfo.objects.get(username=username)
    forums= Forum.objects.filter(user=user)
    if user.gender == 'M':
        user.gender = '男'
    else:
        user.gender = '女'
    return render(request, 'user/index.html', locals())


@check_login
def modify(request):
    user = UserInfo.objects.get(username=request.session['userName'])
    if request.method == 'GET':
        return render(request, 'user/modify.html', locals())
    elif request.method == 'POST':
        data = request.POST
        user.age = data.get('age')
        user.nickname = data.get('nickname')
        user.gender = data.get('gender')
        user.save()
        return HttpResponseRedirect('/user/index')


@check_login
def changePassword(request):
    # 后续改成用userID索引用户，因为id有索引
    user = UserInfo.objects.get(username=request.session['userName'])
    if request.method == 'GET':
        return render(request, 'user/changePassword.html', locals())
    elif request.method == 'POST':
        password = request.POST.get('password')
        m_password = md5()
        m_password.update(password.encode())
        password = m_password.hexdigest()
        user.password = password
        user.save()
        return HttpResponseRedirect('/user/index')


@check_login
def information(request, username):
    username_myself = request.session['userName']
    '''
        判断两个用户是不是在关系表里,在则是好友关系
    '''
    isFriend = (bool(FriendRelationship.objects.filter(Q(username_A=username) & Q(username_B=username_myself)))
                or bool(FriendRelationship.objects.filter(Q(username_B=username) & Q(username_A=username_myself))))
    # isFriend=False
    if username_myself == username:
        # 是用户自己返回主页
        return HttpResponseRedirect('/user/index')
    # 把用户信息查出来返回前端
    user = UserInfo.objects.get(username=username)
    forums = Forum.objects.filter(user=user)
    if user.gender == 'M':
        user.gender = '男'
    else:
        user.gender = '女'
    return render(request, 'user/information.html', locals())


@check_login
def notifications(request):
    return render(request, 'user/notifications.html')


@check_login
def val_mes(request):
    username = request.session['userName']
    user = UserInfo.objects.get(username=username)
    informs = ValidationMessages.objects.filter(receiver=user)
    return render(request, 'user/val_mes.html', locals())


# 增加搜索用户
@check_login
def search_user(request):
    try:
        username = request.GET.get('username')
        user = UserInfo.objects.get(username=username)
        data = {
            "username": username,
            "nickname": user.nickname,
            "gender": '男' if user.gender == 'M' else '女',
            "age": user.age,
        }
        return HttpResponse(json.dumps(data, ensure_ascii=False))
    except:
        return HttpResponse(404)

user/templates/user/addFriend.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

user/templates/user/index.html
<!doctype html>
<html lang="zh-hans">
{% extends 'base.html' %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
    <title>个人主页</title>
    {% endblock title %}
    {% block style %}
    <link rel="stylesheet" href="{% static 'css/classSchedule.css' %}">
    <link rel="stylesheet" href="{% static 'css/index-modify.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- bootstrap5设置不了列偏移 这里改为bootstrap3-->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
    <!-- 导入bootstrap.js -->
    <style>
        p {
            text-align: center;
        }
    </style>
    {% endblock style %}
</head>

<body>
    {% block content %}
    <center><button id='get_info' class='btn btn-success'>查看信息</button></center>
    <div class="container mt-2" id="info_container" hidden>
        <table>
            <tr>
                <th>用户名</th>
                <th>昵称</th>
                <th>年龄</th>
                <th>性别</th>
                <th>邮箱</th>
            </tr>
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.nickname }}</td>
                <td>{{ user.age }}</td>
                <td>{{ user.gender }}</td>
                <td>{{ user.email }}</td>
            </tr>
        </table>
        <div class="text-center mt-3">
            <a class="text-decoration-none btn btn-warning" href="{% url 'user:modify' %}">修改信息</a>
            <a class="text-decoration-none btn btn-danger" href="{% url 'user:changePassword' %}">修改密码</a>
            <button class='btn btn-secondary' id='back'>收起</button>
        </div>
    </div>
    <div class="container mt-3">
        <center class="">
            <a class="col-md-2 col-md-offset-2 text-decoration-none btn btn-primary"
                href="{% url 'friends:friends_list' %}">好友列表</a>
            <a class="col-md-2 text-decoration-none btn btn-info" href="{% url 'user:notifications' %}">消息/通知</a>
            <button type="button" class="btn btn-primary col-md-2" data-bs-toggle="modal" data-bs-target="#myModal">
                搜索用户
            </button>
            <button class="col-md-2 text-decoration-none btn btn-danger" id="show-forums">我的文章</button>

            <!-- 模态框 -->
            <div class="modal fade" id="myModal">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <!-- 模态框头部 -->
                        <div class="modal-header">
                            <h5 class="modal-title text-secondary">搜索用户</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                        </div>

                        <!-- 模态框内容 -->
                        <div class="modal-body">
                            <div class="container" id='user-search-container'>
                                <div class="row">
                                    <div class="col-md-10">
                                        <input type="text" id='search-box-username' class="form-control mt-2"
                                            placeholder="请输入要查找的用户名">
                                    </div>
                                    <div class="col-md-2">
                                        <input type="submit" name="username" id="search-box-submit" value="查询"
                                            class="btn btn-primary  ">
                                    </div>
                                </div>
                                <table class="table table-striped table-bordered table-hover mt-4" style="width:100%"
                                    id='search-results-table' hidden>

                                    <tr style="height: 10px;">
                                        <td class="col-6 text-center">用户名</td>
                                        <td class="col-6 text-center" id="td-username">123</td>
                                    </tr>
                                    <tr>
                                        <td class="col-6 text-center">昵称</td>
                                        <td class="col-6 text-center" id="td-nickname"></td>

                                    </tr>
                                    <tr>
                                        <td class="col-6 text-center">性别</td>
                                        <td class="col-6 text-center" id="td-gender"></td>
                                    </tr>
                                    <tr>
                                        <td class="col-6 text-center">年龄</td>
                                        <td class="col-6 text-center" id="td-age"></td>
                                    </tr>
                                    <tr>
                                        <td class="col-6 text-center" colspan="2">
                                            <a href="#" class="btn btn-primary" id='td-index'>TA的主页</a>
                                        </td>
                                        <!-- <td class="col-6 text-center"><a href="#">添加好友</a></td> -->
                                    </tr>

                                    <!-- <td class="col-6"></td> -->
                                </table>
                            </div>
                        </div>
        </center>

    </div>
    <div class="container mt-5">
        <div class="row">
            <div id="forums" class="mx-auto bg-dark text-center text-warning w-50 border border-3 border-secondary" hidden>
                {% for forum in forums %}
                <p class="mt-3  text-start"><a href="{% url 'forum:detail' forum.id %}" class="btn btn-warning">{{ forum.title }}</a></p>
                {% empty %}
                <h3 class="text-danger">还没有写过文章哦！</h3>
                {% endfor %}
                <button class="btn btn-secondary" id="hide-forums">收回</button>
            </div>
        </div>
    </div>
    
    {% endblock content %}
    {% block script %}
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js"></script>
    <script>
        // 查看信息,显示/收回
        var get_info = $('#get_info');
        var back = $('#back');

        get_info.bind('click', function () {
            $('#info_container').prop('hidden', false);
        })
        back.bind('click', function () {
            $('#info_container').prop('hidden', true);
        })

        // 搜索用户模态框的一系列操作
        $("#search-box-username").bind('focus', function () {
            $("#search-results-table").prop("hidden", true);
        });
        $("#search-box-submit").bind("click", function () {
            var username = $("#search-box-username").val();
            $.get("{% url 'user:search_user' %}", { "username": username }, function (res) {
                if (res == 404) {
                    alert("用户不存在！")
                }
                else {
                    var data = $.parseJSON(res);
                    $("#td-username").text(data.username);
                    $("#td-nickname").text(data.nickname);
                    $("#td-gender").text(data.gender);
                    $("#td-age").text(data.age);
                    $("#td-index").attr('href', "/user/information/" + data.username + '/');
                    $("#search-results-table").prop("hidden", false);
                }

            });
        });
        // 显示我的文章列表
        $("#show-forums").bind("click", function () {
            $("#forums").prop("hidden", false);
        })
        $("#hide-forums").bind("click", function () {
            $("#forums").prop("hidden", true);
        })
    </script>
    {% endblock script %}
</body>

</html>

user/templates/user/notifications.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>消息</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-2 col-md-offset-3 bg-warning text-center">
                <a href="{%url 'user:val_mes' %}" class=" text-danger text-decoration-none">好友验证消息</a>
            </div>
            <div class="col-md-2 bg-success text-center">
                <a href="{% url 'friends:dialogues' %}" class="text-dark text-decoration-none">聊天消息</a>
            </div>
            <div class="col-md-2 bg-secondary text-center">
                <a href="#" class="text-decoration-none text-danger">通知</a>
            </div>
        </div>
    </div>
</body>

</html>

user/templates/user/val_mes.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>我的消息</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.js"></script>
</head>

<body>
    {% for inform in informs %}
    <!-- 判断消息类型,是别人申请加好友机isAgree=W时,才应该有同意和拒绝的选项 -->
    {% ifequal inform.isAgreed "W" %}
    <div class="container">
        <div class="bg-dark text-warning col-5">
            <div class="m-2 text-info">发送人:{{ inform.sender }}</div>
            <div class="m-2 text-danger">内容:{{ inform.content }}</div>
            <div class="m-2 text-muted">时间:{{ inform.send_time }}</div>
            <div class='text-center mt-3'>
                <button id='agree{{ forloop.counter }}' class="btn btn-success">同意</button>
                <button id="reject{{ forloop.counter }}" class="btn btn-warning">婉拒</button>
            </div>
        </div>
    </div>

    <script>

        agree = document.getElementById('agree{{ forloop.counter }}');
        reject = document.getElementById('reject{{ forloop.counter }}');
        function confirm_agree() {
            if (confirm('确定添加{{ inform.sender }}为好友吗?')) {
                // ajex技术刷新
                // js 发送http请求

                $.post("{% url 'friends:agree' %}", { "id": "{{ inform.id }}", "sender": "{{ inform.sender }}", "receiver": "{{ inform.receiver }}" });
                location.reload();

            }
        }
        function confirm_reject() {
            if (confirm('确定拒绝添加{{ inform.sender }}为好友吗?\n')) {

                $.post("{% url 'friends:reject' %}", { "id": "{{ inform.id }}", "sender": "{{ inform.sender }}", "receiver": "{{ inform.receiver }}" });
                location.reload();
            }
        }
        agree.onclick = confirm_agree;
        reject.onclick = confirm_reject;

    </script>
    {% else %}
    <div class="container">
        <span class="bg-dark text-warning p-2 m-3 ">{{ inform.content }} &nbsp;时间:{{ inform.send_time }}</span>
        <button id='delete{{ forloop.counter }}' class='btn btn-danger'>删除</button>
    </div>
    <script>
        $("#delete{{ forloop.counter }}").bind("click", function () {
            $.post("{% url 'friends:del_val_mes' %}", { "id": "{{ inform.id }}" });
            location.reload();
        })
    </script>

    {% endifequal %}
    {% empty %}
    <div class="container mt-5">
        <h3>当前没有要处理的消息</h3>
        <a href="{% url 'user:notifications' %}" class='btn btn-primary text-decoration-none'>返回</a>
    </div>

    {% endfor %}

</body>

</html>