cs/urls.py
from django.urls import path
# from django.contrib import
from .views import *

app_name='cs'
urlpatterns = [
    path('index',index,name='index'),
    path('classSchedule', classSchedule,name='classSchedule'),
    path('javaDocumentation', javaDocumentation,name='javaDocumentation'),
    path('javaExam',javaExam,name='javaExam'),
]

friends/urls.py
from django.urls import path

from forum.views import delete
from .views import *

app_name = 'friends'
urlpatterns = [
    path('friends_list', friends_list, name='friends_list'),
    path('add_friend/<str:username>', add_friend, name='add_friend'),
    path('agree', agree, name="agree"),
    path('reject', reject, name='reject'),
    path('del_val_mes', del_val_mes, name="del_val_mes"),
    path('delete_friend/<str:username>', delete_friend, name='delete_friend'),
    path('dialogues', dialogues, name='dialogues'),
    path('detail_dialogues', detail_dialogues, name='detail_dialogues'),
    path('send_message', send_message, name='send_message'),
    path('set_remark_name', set_remark_name, name='set_remark_name'),
]

myforum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("firstTest.urls")),
    path('forum/', include("forum.urls")),
    path('user/', include("user.urls")),
    path('cs/', include('cs.urls')),
    path('loveBar/', include('loveBar.urls')),
    path('xlTree/', include('xlTree.urls')),
    path('comment/', include('comment.urls')),
    path('friends/',include('friends.urls')),
    # path('get_file/')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *
app_name='user'
urlpatterns = [
    path('register',register,name='register'),
    path('login',login,name='login'),
    path('logout',logout,name='logout'),
    path('index',index,name='index'),
    path('modifyUserInfo',modify,name='modify'),
    path('changePassword',changePassword,name='changePassword'),
    path('information/<str:username>/',information,name='information'),
    path('notifications',notifications,name='notifications'),
    path('val_mes',val_mes,name='val_mes'),
    path('search_user',search_user,name='search_user'),
]

friends/models.py
from django.db import models

# Create your models here.
from user.models import UserInfo


class FriendRelationship(models.Model):
    '''
        关系表，只记录两个用户的用户名和成为朋友关系的时间
        及互相的备注名
    '''
    username_A = models.CharField(verbose_name='用户A', max_length=20)
    username_B = models.CharField(verbose_name='用户B', max_length=20)
    remark_name_A = models.CharField(verbose_name='A的备注', max_length=20, null=True)
    remark_name_B = models.CharField(verbose_name='B的备注', max_length=20, null=True)
    added_time = models.DateTimeField(verbose_name='添加时间', auto_now_add=True)
    # isActive = models.BooleanField('是否有效', default=True, choices=((True, '是'), (False, '否')))

    class Meta:
        db_table = 'FR'  # FriendRelationship
        verbose_name = '好友关系'
        verbose_name_plural = '好友关系'
        ordering = ["added_time"]


# class Friend(models.Model):
#
#     user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
#     username = models.CharField(verbose_name='用户名', max_length=20)
#     remarkName = models.CharField(verbose_name='昵称', max_length=20, null=True)
#     added_time = models.DateTimeField(verbose_name='添加时间', auto_now_add=True)
#
#     class Meta:
#         db_table = 'friends'
#         verbose_name = '好友'
#         verbose_name_plural = '好友'
#         ordering = ['user', "added_time"]


class ValidationMessages(models.Model):
    '''
        获取发送好友请求的人，接受的信息的人，将验证信息渲染再接收者的页面
    '''
    sender = models.ForeignKey(UserInfo, related_name='sender', on_delete=models.CASCADE)
    receiver = models.ForeignKey(UserInfo, related_name='receiver', on_delete=models.CASCADE)
    content = models.TextField(verbose_name='消息')
    send_time = models.DateTimeField(verbose_name='发送时间', auto_now_add=True)
    isAgreed = models.CharField(verbose_name='是否同意',max_length=1, default='W',
                                choices=(('W', '等待'), ('Y', '同意'),('N','拒绝')))

    # 根据是否同意确定是否成为好友关系
    class Meta:
        db_table = 'val_mes'


class Dialogue(models.Model):
    sender = models.ForeignKey(UserInfo, related_name='dialogue_user', on_delete=models.CASCADE)
    receiver = models.ForeignKey(UserInfo, related_name='dialogue_friend', on_delete=models.CASCADE)
    message = models.TextField(verbose_name='消息')
    send_time = models.DateTimeField(verbose_name='发送时间', auto_now_add=True)
    '''
        根据user和friend按日期查询出结果并渲染
    '''
    '''
        当用户点击某个好友时，将与该好友的对话进行渲染
        两个好友的全部对话按按时间顺序渲染。
    '''

    class Meta:
        db_table = 'dialogue'

friends/views.py
import json

from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.http import Http404

# Create your views here.
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from user.views import check_login
from user.models import UserInfo
from .models import *
from django.db.models import Q, F


@check_login
def friends_list(request):
    username = request.session['userName']

    # friends=FriendRelationship.objects.filter(Q(FriendRelationship.username_A=='username'
    #                                             | Q(FriendRelationship.username_B)))
    friends = [{"username": fr.username_B, "remarkName": fr.remark_name_B} for fr in
               FriendRelationship.objects.filter(username_A=username)]
    friends += [{"username": fr.username_A, "remarkName": fr.remark_name_A} for fr in
                FriendRelationship.objects.filter(username_B=username)]

    return render(request, 'friends/friends_list.html', locals())


@check_login
def add_friend(request, username):
    sender = UserInfo.objects.get(username=request.session['userName'])
    receiver = UserInfo.objects.get(username=username)
    if request.method == 'GET':
        return render(request, 'friends/validationMessage.html', locals())
    elif request.method == 'POST':
        # 添加好友时在两个用户之间建立一个验证消息会话
        # 即在数据库中新建一条会话记录
        content = request.POST.get('content', f'{sender}请求添加你为好友！')
        ValidationMessages.objects.create(sender=sender, receiver=receiver, content=content)
        print(content)
        return HttpResponseRedirect('/friends/friends_list')


@csrf_exempt
def agree(request):
    if request.method == "POST":
        data = request.POST
        inform_id = data.get('id')
        sender = UserInfo.objects.get(username=data.get("sender"))
        receiver = UserInfo.objects.get(username=data.get("receiver"))

        '''
            该条验证消息对接收者已经没有意义
            讲该条验证消息的是否同意设置为Y,修改验证消息为“xxx同意了你的好友请求”,
            互换接受者和发送者身份,这样发送者就会收到来自接收者的回馈消息
        '''
        val_mes = ValidationMessages.objects.get(id=inform_id)
        val_mes.isAgreed = 'Y'
        val_mes.content = f"{receiver.username}通过了你的好友验证！"
        val_mes.sender, val_mes.receiver = receiver, sender
        val_mes.save()

        # 若fr关系表中没有这对关系则在fr表中建立sender和receiver的朋友关系
        try:
            FriendRelationship.objects.get(username_A=sender.username, username_B=receiver.username)
        except:
            try:
                FriendRelationship.objects.get(username_A=receiver.username, username_B=sender.username)
            except:
                FriendRelationship.objects.create(username_A=sender.username, username_B=receiver.username,
                                                  remark_name_A=sender.username, remark_name_B=receiver.username)
        return HttpResponse(200)


@csrf_exempt
def reject(request):
    if request.method == "POST":
        data = request.POST
        inform_id = data.get('id')
        sender = UserInfo.objects.get(username=data.get("sender"))
        receiver = UserInfo.objects.get(username=data.get("receiver"))

        '''
            该条验证消息对接收者已经没有意义
            讲该条验证消息的是否同意设置为N,修改验证消息为“xxx婉拒了你的好友请求”,
            互换接受者和发送者身份,这样发送者就会收到来自接收者的回馈消息
        '''
        val_mes = ValidationMessages.objects.get(id=inform_id)
        val_mes.isAgreed = 'N'
        val_mes.content = f"{receiver.username}婉拒了你的好友请求！"
        val_mes.sender, val_mes.receiver = receiver, sender
        val_mes.save()
        print('123')

        return HttpResponse(200)


@csrf_exempt
def del_val_mes(request):
    if request.method == "POST":
        val_mes_id = request.POST.get('id')
        ValidationMessages.objects.get(id=val_mes_id).delete()
        # 返回一个响应防止报错
        return HttpResponse(200)


@check_login
def delete_friend(request, username):
    # 获取session中的当前用户名和参数用户名
    # 在数据库中删除这对好友关系
    username_myself = request.session.get('userName')
    print(username)
    try:
        fr = FriendRelationship.objects.get(username_A=username_myself, username_B=username)
        fr.delete()
        return HttpResponseRedirect('/friends/friends_list')
    except:
        try:
            fr = FriendRelationship.objects.get(username_B=username_myself, username_A=username)
            fr.delete()
            return HttpResponseRedirect('/friends/friends_list')

        except:
            return render(request, '404.html')


@check_login
def dialogues(request):
    '''
    查询出与该用户有过聊天的用户,去重后渲染出对话框
    '''
    user_id = request.session.get('userID')
    user = UserInfo.objects.get(id=user_id)
    receivers = list(map(lambda x: x.receiver, Dialogue.objects.filter(sender=user)))
    senders = list(map(lambda x: x.sender, Dialogue.objects.filter(receiver=user)))
    related_users = list(set(receivers + senders))

    dialogues_list = []  # 定义一个空列表存需要渲染的对话框数据
    for related_user in related_users:
        # 根据相关用户查询出与该用户最新一条消息记录和发送时间
        dia = Dialogue.objects.filter(
            Q(sender=related_user) & Q(receiver=user) | Q(sender=user) & Q(receiver=related_user)).order_by(
            '-send_time')[0]
        dialogues_list.append({
            "user": related_user,
            "message": dia.message,
            "send_time": dia.send_time,

        })

    return render(request, 'friends/dialogues.html', context={'dialogues': dialogues_list})


@check_login
def detail_dialogues(request):
    '''
    查询出这两个用户之间的所有对话
    按时间排序渲染在对话框中
    '''
    try:
        user = UserInfo.objects.get(username=request.session.get('userName'))
        related_user = UserInfo.objects.get(username=request.GET.get('username'))

        dialogue_objects = Dialogue.objects.filter(
            Q(sender=related_user) & Q(receiver=user) | Q(sender=user) & Q(receiver=related_user)).order_by(
            'send_time')
        dialogues_list = []
        for dialogue_object in dialogue_objects:
            dialogues_list.append({
                "username": dialogue_object.sender.username,
                "message": dialogue_object.message,
                "send_time": str(dialogue_object.send_time),
            })
        print(json.dumps(dialogues_list))
        return HttpResponse(json.dumps(dialogues_list))
    except:
        return render(request, '404.html')


# @check_login
@csrf_exempt
def send_message(request):
    '''
    接受ajax请求,存储发送过来的ajax对话数据
    '''
    sender_name = request.POST.get("send_name")
    receiver_name = request.POST.get("receiver_name")
    sender = UserInfo.objects.get(username=sender_name)
    receiver = UserInfo.objects.get(username=receiver_name)
    message = request.POST.get("message")
    Dialogue.objects.create(sender=sender, receiver=receiver, message=message)
    return HttpResponse(200)


# TODO:解决csrf_exempt装饰的视图函数的跨站请求伪造问题

@csrf_exempt
def set_remark_name(request):
    data = request.POST
    user = data.get('username')
    friend = data.get('friendUsername')
    remarkName = data.get('remarkName')
    print(user,friend,remarkName)
    try:
        fr = FriendRelationship.objects.get(username_A=user, username_B=friend)
        fr.remark_name_B = remarkName
        fr.save()
        return HttpResponse("success")
    except:
        try:
            fr = FriendRelationship.objects.get(username_A=friend, username_B=user)
            fr.remark_name_A = remarkName
            fr.save()
            return HttpResponse("success")
        except:
            return HttpResponse(404)

friends/templates/friends/dialogues.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>聊天消息</title>
    <link href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.js"></script>

</head>

<body>
    {% for dialogue in dialogues %}

    <div class="container mt-3 btn" style="width:50%" id='dialogue-{{ dialogue.user }}' data-bs-toggle="modal"
        data-bs-target="#myModal-{{ dialogue.user }}" data-bs-toggle="tooltip" data-bs-placement="top" title="单击展开哦!">
        <div class="card bg-warning">
            <div class="card-header">{{ dialogue.user }}</div>
            <div class="card-body">{{ dialogue.message }}</div>
            <div class="card-footer">{{ dialogue.send_time }}</div>
        </div>
    </div>

    <!-- 模态框做聊天框-->
    <div class="modal" id="myModal-{{ dialogue.user }}">
        <div class="modal-dialog modal-dialog-scrollable modal-l">
            <div class="modal-content">

                <!-- 模态框头部 -->
                <div class="modal-header">
                    <h4 class="modal-title">好友聊天框<small>({{ dialogue.user }})</small></h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                        id='close-{{ dialogue.user }}'></button>
                </div>

                <!-- 模态框内容 -->
                <div class="modal-body" id="detail-{{ dialogue.user }}">

                </div>

                <!-- 模态框底部 -->
                <div class="modal-footer">
                    <input type="text" name='message' id="message-{{ dialogue.user }}" class=" form-control mt-1"
                        placeholder="在此输入消息" style="width:80%;height:50px">
                    <button type="button" class="btn btn-danger" id="send-{{ dialogue.user }}">发送</button>
                </div>

            </div>
        </div>
    </div>

    <script>

        $("#dialogue-{{ dialogue.user }}").bind("click", function () {
            // 先清空原来的数据,防止重复渲染
            $("#detail-{{ dialogue.user }}").html("");
            var username = "{{ dialogue.user }}";
            // 发送get请求已有对话记录
            $.get("{% url 'friends:detail_dialogues' %}", { "username": username }, function (res) {
                var data = $.parseJSON(res);

                if ($.isEmptyObject(data)) {
                    $("#detail-{{ dialogue.user }}").html("<h2>还没有消息记录哦！</h2>");
                }
                for (i = 0; i < data.length; i++) {
                    sender = "<span class='h5 mr-3'>" + data[i].username + "</span>";
                    send_time = "&nbsp;&nbsp;&nbsp;&nbsp;<span class='small secondary'>" + data[i].send_time + "</span>";

                    if (data[i].username == username) {
                        message = "<div class='mt-1 mb-4 text-primary'>" + data[i].message + "</div>";
                    }
                    else {
                        message = "<div class='mt-1 mb-4 text-success'>" + data[i].message + "</div>";
                    }
                    // 将消息记录逐条添加到模态框内容里
                    $("#detail-{{ dialogue.user }}").append(
                        sender + send_time + message
                    );
                }
            });
        });

        $("#send-{{ dialogue.user }}").bind('click', function () {
            var message = $("#message-{{ dialogue.user }}").val();
            var sender_name = "{{ request.session.userName }}";
            var receiver_name = "{{ dialogue.user }}";
            // 发送post请求给后端,传递上述参数
            $.post("{% url 'friends:send_message' %}", { "send_name": sender_name, "receiver_name": receiver_name, "message": message }, function (res) {

                $("#message-{{ dialogue.user }}").val("");
                $("#dialogue-{{ dialogue.user }}").click();
            })
        })

    </script>


    {% empty %}
    你还没有聊天记录
    {% endfor %}
</body>

</html>

friends/templates/friends/friends_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>好友列表</title>
    <link href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.js"></script>
</head>

<body>

    <ul>
        {% for friend in friends %}
        <div class="mt-3">
            <a href="{% url 'user:information' friend.username %}" class="btn btn-success text-dark text-start w-25">{{ friend.username }}<small class="text-light">({{ friend.remarkName }})</small></a>
            <a class="btn btn-warning w-20" data-bs-toggle="modal"
                data-bs-target="#remark-{{ friend.username }}">
                修改备注
            </a>
            <button id="delete-friend" class="btn btn-danger w-20 "> 删除</button>
            <a class="btn btn-info w-20" id='dialogue-{{ friend.username }}' data-bs-toggle="modal"
                data-bs-target="#myModal-{{ friend.username }}">
                发消息
            </a>
        </div>
        <div class="modal" id="myModal-{{ friend.username }}">
            <div class="modal-dialog modal-dialog-scrollable modal-l">
                <div class="modal-content">

                    <!-- 模态框头部 -->
                    <div class="modal-header">
                        <h4 class="modal-title">好友聊天框<small class='text-secondary'>({{ friend.remarkName }})</small>
                        </h4>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                            id='close-{{ friend.username }}'></button>
                    </div>

                    <!-- 模态框内容 -->
                    <div class="modal-body" id="detail-{{ friend.username }}">

                    </div>

                    <!-- 模态框底部 -->
                    <div class="modal-footer">
                        <input type="text" name='message' id="message-{{ friend.username }}" class=" form-control mt-1"
                            placeholder="在此输入消息" style="width:80%;height:50px">
                        <button type="button" class="btn btn-danger" id="send-{{ friend.username }}">发送</button>
                    </div>

                </div>
            </div>
        </div>
        <div id="remark-{{ friend.username }}" class="modal">
            <div class="modal-dialog">
                <div class="modal-content">
            
                    <!-- 模态框头部 -->
                    <div class="modal-header">
                        <h5 class="modal-title">设置备注</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                    </div>
            
                    <!-- 模态框内容 -->
                    <div class="modal-body">
                        <input type="text" name="remark_name" id="remark_name_{{ friend.username }}"  class="form-control mx-auto w-50 h-100" placeholder="请输入要设置的备注名">
                    </div>
            
                    <!-- 模态框底部 -->
                    <div class="mx-auto">
                        <button type="button" class="btn btn-primary" id="remark_name_btn_{{ friend.username }}" >设置</button>
                    </div>
            
                </div>
            </div>
        </div>
        <script>

            $("#dialogue-{{ friend.username }}").bind("click", function () {
                // 先清空原来的数据,防止重复渲染
                $("#detail-{{ friend.username }}").html("");
                var username = "{{ friend.username }}";
                $.get("{% url 'friends:detail_dialogues' %}", { "username": username }, function (res) {
                    var data = $.parseJSON(res);
                    if ($.isEmptyObject(data)) {
                        $("#detail-{{ friend.username }}").html("<h4 class='text-warning'>还没有消息记录哦！</h4>");
                    }
                    for (i = 0; i < data.length; i++) {
                        sender = "<span class='h5 mr-3'>" + data[i].username + "</span>";
                        send_time = "&nbsp;&nbsp;&nbsp;&nbsp;<span class='small secondary'>" + data[i].send_time + "</span>";

                        if (data[i].username == username) {
                            message = "<div class='mt-1 mb-4 text-primary'>" + data[i].message + "</div>";
                        }
                        else {
                            message = "<div class='mt-1 mb-4 text-success'>" + data[i].message + "</div>";
                        }
                        $("#detail-{{ friend.username }}").append(
                            sender + send_time + message
                        );
                    }
                });
            });

            $("#send-{{ friend.username }}").bind('click', function () {
                var message = $("#message-{{ friend.username }}").val();
                var sender_name = "{{ request.session.userName }}";
                var receiver_name = "{{ friend.username }}";
                // 发送post请求给后端,传递上述参数
                $.post("{% url 'friends:send_message' %}", { "send_name": sender_name, "receiver_name": receiver_name, "message": message }, function (res) {

                    $("#message-{{ friend.username }}").val("");
                    $("#dialogue-{{ friend.username }}").click();
                })
            });
            $("#delete-friend").bind("click", function () {
                    if (confirm("确定删除该好友吗!")) {
                        
                        $.get("{% url 'friends:delete_friend' friend.username %}",function(){
                            alert("已删除！");
                            location.reload();
                        });
                      
                    }
                });
            $("#remark_name_btn_{{ friend.username }}").bind("click", function(){
                var username="{{ request.session.userName }}";
                var friendUsername="{{ friend.username }}";
                var remarkName=$("#remark_name_{{ friend.username }}").val();
                $.post("{% url 'friends:set_remark_name' %}",{"username":username,"friendUsername":friendUsername,"remarkName":remarkName},function(res){
                    if (res=="success") {
                        alert("设置成功！");
                        location.reload();
                    }
                });
            });


        </script>
        {% empty %}
        <p>还没有好友</p>
        {% endfor %}
    </ul>
</body>

</html>

friends/templates/friends/validationMessage.html
<!DOCTYPE html>
<html lang="zh-hans">

<head>
    <meta charset="UTF-8">
    <title>验证消息</title>
</head>

<body>
    <form action="" method="post" id="form">
        <input type="text" name="username_A" readonly hidden>
        <input type="text" name="username_B" readonly hidden>
        <textarea name="content" id="" cols="30" rows="10">我是{{ request.session.userName }},希望添加你为好友！</textarea>
        <input type="submit" value="发送">
        {% csrf_token %}

    </form>
</body>

</html>